runtime: python37

runtime_config:
  python_version: 3.7

instance_class: B8
manual_scaling:
  instances: 5
  
env_variables:
  BUCKET_NAME: "stockcsv"
  
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 3
  disk_size_gb: 10
   
