runtime: python37

instance_class: F2

env_variables:
  BUCKET_NAME: "stockcsv"
  
 manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 3
  disk_size_gb: 10
   
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
